CREATE DATABASE Veiculos;

USE Veiculos;

CREATE TABLE Empresa
(	
	idEmpresa INT PRIMARY KEY IDENTITY
	,Veiculo  VARCHAR(200)NOT NULL
);
CREATE TABLE Cliente
(
	idCliente  INT PRIMARY KEY IDENTITY
	,idEmpresa INT FOREIGN KEY REFERENCES Empresa(idEmpresa)
	,Nome	   VARCHAR(200)NOT NULL
	,Cpf 	   VARCHAR(250)NOT NULL
);