CREATE DATABASE Pessoa;

USE Pessoa;

CREATE TABLE Pessoas
(
	idPessoa INT PRIMARY KEY IDENTITY
	,CNH		 VARCHAR(200)NOT NULL
);

CREATE TABLE Dados
(
	idDados		INT PRIMARY KEY IDENTITY
	,idPessoa	INT FOREIGN KEY REFERENCES Pessoas(idPessoa)
	,Email		VARCHAR(200)NOT NULL
	,Telefone	VARCHAR(250)NOT NULL
);
